insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Elmside', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Russell', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Homewood', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Nancy', 'Santo Tomas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Golf View', 'La Concepcion', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Division', 'Benito Juarez', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dixon', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lotheville', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Canary', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sloan', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Monica', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Pine View', 'La Concepcion', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lukken', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bowman', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dakota', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Graceland', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dryden', 'San Martin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Gina', 'Santo Tomas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Prentice', 'San Pedro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Holmberg', 'Santo Tomas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hagan', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hanover', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thackeray', 'Pueblo Nuevo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Coolidge', 'San Pedro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Anhalt', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hudson', 'Benito Juarez', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mcbride', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Forest Dale', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Rutledge', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Miller', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mifflin', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Russell', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Park Meadow', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Raven', 'San Pedro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mesta', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Granby', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hayes', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Shelley', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Atwood', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Warbler', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sauthoff', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Division', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Florence', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thackeray', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('John Wall', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Susan', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sunfield', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('6th', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bluejay', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mockingbird', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Truax', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Crowley', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ilene', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Union', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Elgar', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Fulton', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Kedzie', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lighthouse Bay', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Moland', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lakeland', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thackeray', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Summit', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Merry', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northridge', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Gulseth', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Myrtle', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lakewood', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hoffman', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Grayhawk', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hanover', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Farmco', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Scott', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Killdeer', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sutteridge', 'La Virgen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Delaware', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Waxwing', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Farwell', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Montana', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Gina', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northwestern', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Eagan', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mifflin', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Maryland', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Corry', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Helena', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Straubel', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Morning', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Weeping Birch', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Old Gate', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Straubel', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Monica', 'La Virgen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sullivan', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hudson', 'La Virgen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Prairie Rose', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Stang', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dennis', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sullivan', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hermina', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Little Fleur', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Reindahl', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dwight', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Stone Corner', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Melby', 'San Martin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Waxwing', 'Benito Juarez', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Melby', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Oriole', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('High Crossing', 'La Palma', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Magdeline', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Linden', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Debs', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Stoughton', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Clarendon', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Grasskamp', 'La Concepcion', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Cambridge', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Main', 'La Palma', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thierer', 'San Pedro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Brentwood', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thackeray', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Crowley', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Londonderry', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Moulton', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Buhler', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Colorado', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Goodland', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Charing Cross', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Delladonna', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ridgeway', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bartelt', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Brown', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sullivan', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Nevada', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Butternut', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Westridge', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Twin Pines', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dahle', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Schmedeman', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Eastlawn', 'San Pedro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Springview', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Forest Dale', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Comanche', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bluejay', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Miller', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ridgeview', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Cambridge', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Kensington', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bobwhite', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Vera', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Scofield', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Cherokee', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Roxbury', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sommers', 'La Concepcion', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Prairieview', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Tomscot', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Redwing', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hovde', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northridge', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Surrey', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Alpine', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lindbergh', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Spenser', 'Pueblo Nuevo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Scoville', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mitchell', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Spaight', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Derek', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Badeau', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ryan', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Annamark', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Upham', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Grasskamp', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Clarendon', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Saint Paul', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lighthouse Bay', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Independence', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northwestern', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Myrtle', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Evergreen', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Helena', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Reinke', 'Lazaro Cardenas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Stephen', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Eastwood', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Londonderry', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mcguire', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Walton', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Oxford', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Comanche', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Independence', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Holmberg', 'Benito Juarez', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Fulton', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lindbergh', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sage', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Daystar', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Oxford', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dixon', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Forest', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Grayhawk', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Barby', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sherman', 'La Virgen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Moland', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mcbride', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Fisk', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Crest Line', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lakeland', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Summerview', 'La Virgen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ronald Regan', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Atwood', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Amoth', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Namekagon', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northview', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mariners Cove', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Utah', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Marcy', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hanover', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Buena Vista', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bartelt', 'San Lorenzo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('David', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lunder', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mcbride', 'Independencia', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Victoria', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Buell', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Haas', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hovde', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Carpenter', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Truax', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Petterle', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Summer Ridge', 'Guadalupe', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sundown', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Clarendon', 'El Mirador', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Doe Crossing', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Morning', 'Santo Tomas', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Farwell', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mesta', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Larry', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Old Shore', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Warrior', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Algoma', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Barnett', 'El Potrero', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Fieldstone', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Tomscot', 'La Palma', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('West', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bultman', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Harper', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Del Mar', 'El Capulin', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('La Follette', 'San Sebastian', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dahle', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Brentwood', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Tony', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Arkansas', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Towne', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Old Gate', 'El Carmen', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Del Sol', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('5th', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Doe Crossing', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northland', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Roth', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Raven', 'Santa Maria', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Loftsgordon', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Swallow', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Cascade', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Memorial', 'San Juan', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Messerschmidt', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Nova', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Kenwood', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Northfield', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Claremont', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('American', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Dottie', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ryan', 'San Francisco', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Scott', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Katie', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Harbort', 'La Palma', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Rieder', 'Ojo de Agua', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lake View', 'Santiago', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Thierer', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Lien', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Elgar', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Merry', 'San Diego', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Bunker Hill', 'Santa Clara', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ronald Regan', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Maryland', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hermina', 'Emiliano Zapata', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mayfield', 'Loma Bonita', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mariners Cove', 'San Antonio', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Schurz', 'Santa Cruz', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sachs', 'La Mesa', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sugar', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Doe Crossing', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Ramsey', 'La Huerta', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Fairview', 'San Isidro', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Veith', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Crowley', 'Hidalgo', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Myrtle', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Sugar', 'La Cañada', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Hallows', 'La Laguna', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Manufacturers', 'Adolfo Lopez Mateos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Manufacturers', 'El Tejocote', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Washington', 'San Miguel', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Mayfield', 'Buenavista', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Kings', 'Isidro Fabela', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Charing Cross', 'Morelos', 'Mexico');
insert into direcciones (calle_direccion, ciudad_direccion, estado_direccion) values ('Nelson', 'La Laguna', 'Mexico');
