insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', '2023-07-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('consequat lectus in est risus auctor sed tristique in tempus', '2023-09-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2022-12-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', '2023-05-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2023-05-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', '2023-09-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', '2023-05-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non', '2023-08-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam', '2023-08-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', '2023-04-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in purus eu magna vulputate luctus cum sociis natoque penatibus et', '2023-01-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '2023-08-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum', '2023-02-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar', '2023-05-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2022-10-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', '2023-02-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', '2023-09-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aenean auctor gravida sem praesent id massa id nisl venenatis', '2022-10-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', '2023-05-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet', '2023-08-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nonummy integer non velit donec diam neque vestibulum eget vulputate ut', '2023-05-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est', '2023-02-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', '2023-06-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae', '2022-12-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', '2023-07-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', '2023-07-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', '2023-01-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', '2022-10-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '2023-03-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', '2022-12-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', '2023-06-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', '2023-07-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', '2022-10-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', '2023-01-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non', '2023-05-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique', '2023-04-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', '2023-01-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', '2022-12-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', '2023-07-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis', '2023-06-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '2023-09-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eleifend pede libero quis orci nullam molestie nibh in lectus', '2022-12-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', '2022-09-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', '2023-08-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', '2023-02-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', '2023-06-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', '2023-07-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('et tempus semper est quam pharetra magna ac consequat metus sapien ut', '2023-05-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '2023-05-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', '2023-04-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', '2023-02-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', '2022-11-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', '2023-06-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', '2023-04-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', '2023-07-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', '2023-06-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', '2023-04-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio', '2023-02-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus', '2023-06-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', '2023-03-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('rutrum nulla nunc purus phasellus in felis donec semper sapien a libero', '2022-12-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', '2023-08-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', '2022-12-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', '2023-08-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '2023-09-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', '2023-08-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eu sapien cursus vestibulum proin eu mi nulla ac enim in', '2023-01-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget', '2023-09-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', '2022-12-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2023-08-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', '2023-06-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', '2023-08-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', '2022-12-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', '2023-04-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam', '2022-11-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', '2023-02-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', '2023-05-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', '2022-12-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', '2022-10-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', '2023-04-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('duis at velit eu est congue elementum in hac habitasse', '2022-09-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nec condimentum neque sapien placerat ante nulla justo aliquam quis', '2023-06-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', '2023-04-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', '2023-05-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', '2023-01-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', '2023-04-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', '2022-09-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', '2022-12-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', '2023-06-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('varius ut blandit non interdum in ante vestibulum ante ipsum primis in', '2023-05-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', '2022-12-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', '2023-02-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium', '2023-04-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet', '2023-07-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('proin at turpis a pede posuere nonummy integer non velit donec diam', '2023-05-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', '2023-06-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', '2023-05-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '2022-11-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit', '2023-02-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', '2023-04-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', '2022-11-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', '2023-05-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing', '2022-12-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', '2023-04-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', '2023-02-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', '2023-08-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '2022-10-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '2022-10-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', '2023-08-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', '2023-07-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vel est donec odio justo sollicitudin ut suscipit a feugiat', '2022-11-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', '2023-09-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', '2023-01-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', '2022-09-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam', '2022-12-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', '2023-02-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer', '2023-04-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy', '2023-06-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in felis eu sapien cursus vestibulum proin eu mi nulla ac', '2023-04-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed', '2023-09-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', '2023-08-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', '2023-07-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', '2022-10-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', '2023-06-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', '2023-07-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', '2023-08-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', '2022-12-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', '2022-10-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', '2022-10-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', '2023-06-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris', '2023-05-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla', '2023-06-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', '2022-10-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at', '2023-05-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula', '2022-10-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '2023-07-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', '2023-09-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', '2023-01-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', '2023-02-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas tristique est et tempus semper est quam pharetra magna ac', '2023-06-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', '2023-05-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', '2023-02-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2023-06-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', '2023-02-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', '2023-01-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', '2023-05-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', '2023-08-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', '2023-03-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', '2023-09-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', '2022-11-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut', '2023-07-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', '2023-01-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', '2023-05-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', '2023-06-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', '2022-12-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc purus phasellus in felis donec semper sapien a libero nam', '2023-07-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('bibendum morbi non quam nec dui luctus rutrum nulla tellus in', '2023-06-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', '2023-06-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', '2022-12-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', '2023-07-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', '2023-04-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo eu massa donec dapibus duis at velit eu est congue elementum in hac', '2023-03-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', '2023-02-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', '2023-06-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', '2023-02-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi', '2022-11-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', '2023-03-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', '2023-02-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', '2022-11-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', '2023-06-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', '2023-03-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', '2023-01-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', '2023-06-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', '2023-01-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', '2023-04-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', '2023-06-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', '2023-02-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus', '2023-01-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu', '2023-09-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', '2023-07-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', '2023-01-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', '2023-02-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', '2023-07-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', '2023-07-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', '2023-05-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', '2023-01-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', '2022-12-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', '2022-10-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', '2023-07-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus', '2022-10-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', '2023-09-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('non sodales sed tincidunt eu felis fusce posuere felis sed lacus', '2023-08-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '2023-05-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', '2022-12-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci', '2023-02-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', '2023-01-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', '2023-07-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', '2022-11-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus', '2023-01-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', '2023-07-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo', '2023-02-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', '2023-07-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', '2023-04-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate', '2023-06-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', '2023-03-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa', '2023-08-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', '2023-02-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non', '2023-02-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '2023-03-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', '2023-08-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum', '2023-04-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', '2023-05-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', '2022-12-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', '2022-12-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras', '2023-09-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2022-09-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', '2022-12-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', '2023-04-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', '2022-11-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lorem quisque ut erat curabitur gravida nisi at nibh in', '2023-05-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', '2022-11-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', '2022-12-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', '2023-05-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', '2022-12-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', '2023-05-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', '2022-10-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien', '2023-01-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', '2023-05-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', '2022-11-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', '2023-04-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '2022-10-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', '2023-02-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('congue etiam justo etiam pretium iaculis justo in hac habitasse platea', '2022-09-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', '2023-08-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dui vel nisl duis ac nibh fusce lacus purus aliquet', '2023-07-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', '2022-11-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio', '2023-01-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', '2023-02-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', '2022-12-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', '2023-07-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2023-01-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', '2022-10-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel', '2023-08-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut ultrices vel augue vestibulum ante ipsum primis in faucibus', '2022-10-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', '2023-07-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', '2023-03-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', '2023-05-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', '2023-05-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', '2023-04-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', '2022-10-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', '2023-08-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', '2023-07-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', '2022-10-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id ligula suspendisse ornare consequat lectus in est risus auctor sed', '2023-02-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', '2022-10-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', '2023-08-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', '2023-02-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('duis at velit eu est congue elementum in hac habitasse', '2023-04-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', '2023-02-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', '2023-07-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut', '2022-11-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', '2023-06-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a', '2023-08-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', '2023-07-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', '2023-05-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', '2022-11-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', '2023-03-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', '2023-04-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis', '2022-09-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', '2023-03-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac', '2023-08-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', '2023-07-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sodales sed tincidunt eu felis fusce posuere felis sed lacus', '2022-12-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', '2023-09-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in ante vestibulum ante ipsum primis in faucibus orci luctus et', '2023-02-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in est risus auctor sed tristique in tempus sit amet', '2022-11-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', '2022-11-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', '2023-08-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis', '2022-09-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', '2023-04-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla', '2022-12-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper', '2023-02-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', '2023-02-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et', '2023-09-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', '2022-10-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', '2023-05-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', '2022-09-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', '2023-01-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', '2023-01-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem', '2022-11-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', '2023-09-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis', '2023-08-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a', '2022-11-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent', '2022-12-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', '2023-02-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', '2022-11-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', '2022-11-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', '2023-01-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu', '2023-08-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet sem fusce consequat nulla nisl nunc nisl duis bibendum', '2023-02-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mi in porttitor pede justo eu massa donec dapibus duis at', '2023-02-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '2023-09-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', '2023-04-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eu sapien cursus vestibulum proin eu mi nulla ac enim in', '2023-05-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('morbi non quam nec dui luctus rutrum nulla tellus in', '2022-10-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '2023-03-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', '2023-04-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', '2022-11-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', '2022-10-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', '2023-09-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem', '2022-12-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', '2023-03-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', '2023-05-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', '2023-05-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis donec semper sapien a libero nam dui proin leo odio porttitor', '2023-05-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', '2023-01-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', '2022-11-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', '2023-04-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', '2022-10-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', '2022-11-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', '2023-07-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa', '2023-07-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', '2023-07-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', '2023-05-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('hac habitasse platea dictumst maecenas ut massa quis augue luctus', '2023-03-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '2023-06-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2023-03-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', '2023-05-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', '2023-09-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', '2023-01-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla', '2022-11-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '2023-05-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', '2023-06-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', '2023-03-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', '2023-02-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', '2023-04-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae mauris viverra diam', '2023-08-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', '2023-04-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', '2022-10-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', '2022-12-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', '2023-02-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('suspendisse ornare consequat lectus in est risus auctor sed tristique in', '2023-04-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', '2023-08-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', '2023-03-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue', '2023-01-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', '2023-04-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas', '2023-07-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum', '2023-03-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', '2023-03-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', '2022-12-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', '2023-04-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis', '2022-12-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', '2022-10-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', '2023-05-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', '2023-07-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu', '2023-05-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', '2023-07-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', '2023-05-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', '2023-03-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('leo odio condimentum id luctus nec molestie sed justo pellentesque viverra', '2023-07-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '2022-12-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', '2023-03-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', '2023-03-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', '2023-06-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', '2022-12-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', '2023-08-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dui proin leo odio porttitor id consequat in consequat ut', '2022-11-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', '2022-10-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum', '2023-02-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', '2022-12-31');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '2022-10-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', '2022-09-30');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', '2023-03-01');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', '2023-03-18');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', '2022-12-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', '2022-10-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', '2023-09-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit', '2023-08-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', '2023-04-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('bibendum morbi non quam nec dui luctus rutrum nulla tellus', '2023-01-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', '2022-09-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', '2022-09-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', '2023-08-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '2023-07-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', '2023-03-05');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sit amet consectetuer adipiscing elit proin interdum mauris non ligula', '2023-02-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tristique est et tempus semper est quam pharetra magna ac', '2023-05-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel', '2023-02-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', '2023-03-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', '2023-01-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', '2023-01-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', '2023-06-11');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', '2023-01-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet', '2023-05-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis', '2023-08-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', '2023-03-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', '2023-05-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', '2023-06-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', '2023-01-22');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2023-04-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', '2022-10-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', '2023-03-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', '2023-07-15');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit', '2023-04-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', '2022-10-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', '2023-07-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', '2023-07-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam', '2023-09-16');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', '2023-04-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', '2023-06-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', '2023-04-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', '2022-10-03');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed', '2022-11-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam', '2022-12-25');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est', '2023-06-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', '2023-01-13');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum', '2023-08-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', '2023-03-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', '2023-03-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', '2022-11-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', '2023-05-04');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', '2023-06-23');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nibh in lectus pellentesque at nulla suspendisse potenti cras in', '2023-04-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', '2023-07-27');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', '2023-05-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue', '2023-08-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac', '2022-12-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', '2022-10-10');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', '2022-12-24');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum', '2022-12-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', '2023-07-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', '2023-09-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', '2023-02-21');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui', '2022-10-09');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', '2022-10-06');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', '2022-10-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse', '2022-10-29');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', '2023-06-12');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', '2023-08-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', '2023-07-14');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', '2023-06-02');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in', '2023-03-19');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('cubilia curae nulla dapibus dolor vel est donec odio justo', '2023-07-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '2023-08-28');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui', '2023-02-20');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', '2023-08-26');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum', '2023-01-08');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', '2023-02-07');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec', '2023-09-17');
insert into resenas (contenido_resena, fecha_publicacion_resena) values ('ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', '2023-02-09');
